// Generated by jextract

package dev.lofthouse.redambergraal.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct gpiod_line_bulk {
 *     struct gpiod_line *lines[64];
 *     unsigned int num_lines;
 * }
 * }
 */
public class gpiod_line_bulk {

    gpiod_line_bulk() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(64, gpiod_h.C_POINTER).withName("lines"),
        gpiod_h.C_INT.withName("num_lines"),
        MemoryLayout.paddingLayout(4)
    ).withName("gpiod_line_bulk");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout lines$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("lines"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct gpiod_line *lines[64]
     * }
     */
    public static final SequenceLayout lines$layout() {
        return lines$LAYOUT;
    }

    private static final long lines$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct gpiod_line *lines[64]
     * }
     */
    public static final long lines$offset() {
        return lines$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct gpiod_line *lines[64]
     * }
     */
    public static MemorySegment lines(MemorySegment struct) {
        return struct.asSlice(lines$OFFSET, lines$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct gpiod_line *lines[64]
     * }
     */
    public static void lines(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, lines$OFFSET, lines$LAYOUT.byteSize());
    }

    private static long[] lines$DIMS = { 64 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * struct gpiod_line *lines[64]
     * }
     */
    public static long[] lines$dimensions() {
        return lines$DIMS;
    }
    private static final VarHandle lines$ELEM_HANDLE = lines$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * struct gpiod_line *lines[64]
     * }
     */
    public static MemorySegment lines(MemorySegment struct, long index0) {
        return (MemorySegment)lines$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * struct gpiod_line *lines[64]
     * }
     */
    public static void lines(MemorySegment struct, long index0, MemorySegment fieldValue) {
        lines$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final OfInt num_lines$LAYOUT = (OfInt)$LAYOUT.select(groupElement("num_lines"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int num_lines
     * }
     */
    public static final OfInt num_lines$layout() {
        return num_lines$LAYOUT;
    }

    private static final long num_lines$OFFSET = 512;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int num_lines
     * }
     */
    public static final long num_lines$offset() {
        return num_lines$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int num_lines
     * }
     */
    public static int num_lines(MemorySegment struct) {
        return struct.get(num_lines$LAYOUT, num_lines$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int num_lines
     * }
     */
    public static void num_lines(MemorySegment struct, int fieldValue) {
        struct.set(num_lines$LAYOUT, num_lines$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

