// Generated by jextract

package dev.lofthouse.redambergraal.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct gpiod_line_event {
 *     struct timespec ts;
 *     int event_type;
 * }
 * }
 */
public class gpiod_line_event {

    gpiod_line_event() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        timespec.layout().withName("ts"),
        gpiod_h.C_INT.withName("event_type"),
        MemoryLayout.paddingLayout(4)
    ).withName("gpiod_line_event");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout ts$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("ts"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct timespec ts
     * }
     */
    public static final GroupLayout ts$layout() {
        return ts$LAYOUT;
    }

    private static final long ts$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct timespec ts
     * }
     */
    public static final long ts$offset() {
        return ts$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct timespec ts
     * }
     */
    public static MemorySegment ts(MemorySegment struct) {
        return struct.asSlice(ts$OFFSET, ts$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct timespec ts
     * }
     */
    public static void ts(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ts$OFFSET, ts$LAYOUT.byteSize());
    }

    private static final OfInt event_type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("event_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int event_type
     * }
     */
    public static final OfInt event_type$layout() {
        return event_type$LAYOUT;
    }

    private static final long event_type$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int event_type
     * }
     */
    public static final long event_type$offset() {
        return event_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int event_type
     * }
     */
    public static int event_type(MemorySegment struct) {
        return struct.get(event_type$LAYOUT, event_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int event_type
     * }
     */
    public static void event_type(MemorySegment struct, int fieldValue) {
        struct.set(event_type$LAYOUT, event_type$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

