// Generated by jextract

package dev.lofthouse.redambergraal.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct gpiod_line_request_config {
 *     const char *consumer;
 *     int request_type;
 *     int flags;
 * }
 * }
 */
public class gpiod_line_request_config {

    gpiod_line_request_config() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        gpiod_h.C_POINTER.withName("consumer"),
        gpiod_h.C_INT.withName("request_type"),
        gpiod_h.C_INT.withName("flags")
    ).withName("gpiod_line_request_config");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout consumer$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("consumer"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *consumer
     * }
     */
    public static final AddressLayout consumer$layout() {
        return consumer$LAYOUT;
    }

    private static final long consumer$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *consumer
     * }
     */
    public static final long consumer$offset() {
        return consumer$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *consumer
     * }
     */
    public static MemorySegment consumer(MemorySegment struct) {
        return struct.get(consumer$LAYOUT, consumer$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *consumer
     * }
     */
    public static void consumer(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(consumer$LAYOUT, consumer$OFFSET, fieldValue);
    }

    private static final OfInt request_type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("request_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int request_type
     * }
     */
    public static final OfInt request_type$layout() {
        return request_type$LAYOUT;
    }

    private static final long request_type$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int request_type
     * }
     */
    public static final long request_type$offset() {
        return request_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int request_type
     * }
     */
    public static int request_type(MemorySegment struct) {
        return struct.get(request_type$LAYOUT, request_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int request_type
     * }
     */
    public static void request_type(MemorySegment struct, int fieldValue) {
        struct.set(request_type$LAYOUT, request_type$OFFSET, fieldValue);
    }

    private static final OfInt flags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("flags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int flags
     * }
     */
    public static final OfInt flags$layout() {
        return flags$LAYOUT;
    }

    private static final long flags$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int flags
     * }
     */
    public static final long flags$offset() {
        return flags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int flags
     * }
     */
    public static int flags(MemorySegment struct) {
        return struct.get(flags$LAYOUT, flags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int flags
     * }
     */
    public static void flags(MemorySegment struct, int fieldValue) {
        struct.set(flags$LAYOUT, flags$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

