#!/usr/bin/env bash
JAVA_OPTS=()
PASSTHROUGH=()

for arg in "$@"; do
    if [[ "$arg" == "--debug" ]]; then
        JAVA_OPTS+=(-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005)
    else
        PASSTHROUGH+=("$arg")
    fi
done

exec ~/.sdkman/candidates/java/current/bin/java \
    --enable-native-access=ALL-UNNAMED \
    "${JAVA_OPTS[@]}" \
    -jar ~/.local/lib/red-amber-graal/red-amber-graal-libgpio.jar "${PASSTHROUGH[@]}"
